install.sh

For me, the x flag on that file produces the following warning each boot:
Aug 02 09:53:12 machine systemd[1]: Configuration file /etc/systemd/system/log2ram.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Without the x flag, everything works fine here. Not sure if your version of systemd has different requirements. If so, feel free to ignore. :-)

no x flag for logr2ram.server

---

log2ram

This pull request resolves azlug/log2ram's issue #6.
- Store sync status directly in the HDD log, to make sure we know
about it if something fails.  This won't help if the HDD_LOG
variable is borked, but it'll help with everything else.
- Made sync a function to avoid repeating five lines three times.
- log2ram now requires (cp or rsync) and tee, mount, umount.

Write sync status to HDD_LOG/log2ram.log.

---

install.sh
log2ram
log2ram.hourly

Since computers crash occasionally, it's probably a good idea to sync
the ramlog back to disk on occasion.  This pull request adds a cron
script to sync the ram log to disk every hour.
Sure, it's more disk activity than only syncing on power off but, for
systems that have days or weeks of uptime, it'll more reliable
overall.  For example, I always suspend my laptop, it only gets turned
off when it crashes, which would mean losing weeks of logfiles.
**Note:** This should be merged after pull request #7.

Sync the ramlog back to disk, hourly.

---

log2ram.service

As requested here: https://github.com/igorpecovnik/lib/commit/9f4a1cb0402e79feb3eec849c6455cc0272e6565
This changes log2ram dependencies to start as early as possible, before other
services that may require access to /var/log, including rsyslog and
systemd-journald.
Additional dependencies on shutdown.target are required to ensure that
the service will be stopped at shutdown/reboot when DefaultDependencies
is set to "no" [[1]].
RequiresMountsFor declares dependency on /var mount when it is a mount point.
IgnoreOnIsolate prevents stopping the service when isolating another unit.
[1]: https://www.freedesktop.org/software/systemd/man/systemd.service.html

Update service dependencies to start on early boot

---

log2ram

I noticed that one of my VMs running log2ram was hanging in boot when trying to start log2ram. I figured that this might have been related to the HDD log dir outgrowing tmpfs and then added a size check in syncFromDisk.
Creating a pull request for it in case it should be of use for anyone else.

Added check of tmpfs size before syncing HDD to RAM.

---

log2ram

Previously, log2ram just exited with error code 1 when the tmpfs was too small during syncFromDisk() at startup. That left, however, the mounts in place and therefore could lead to loss of data. New version removes the mounts upon this error.

unmount tmpfs if RAM too small to prevent corruption of logdir

---

log2ram.hourly

Otherwise, systems that are able to send mails would send the uninteresting output to the admin.

make hourly Cron job quiet

---

log2ram

Suppresses an error message, if the file does not exist.

use rm -f instead of rm

---

install.sh

The last bracket shall not be glued to the directory.
The actual code is generating a runtime error like the following :
erwan@raspberrypi:~/download/log2ram $ sudo ./install.sh
Created symlink /etc/systemd/system/sysinit.target.wants/log2ram.service → /etc/systemd/system/log2ram.service.
./install.sh: 19: [: missing ]
This patch simply adds the missing space to make this script work.

install: Fixing code typo

---

README.md
install.sh
log2ram
log2ram.logrotate
uninstall.sh

Note that the "log2ram.log" is **no** longer automatically deleted at reboot/start.
After installing log2ram, you can force log2ram to delete the all rotation files: "log2ram.log", "log2ram.log.1", etc.
Call:
`log2ram clean-rotate`
**Tip:**
This can also be done right after the installation and _before_ the reboot.
Default rotation is daily for 7 days.

Added logrotate support

---

install.sh

separate checks from execution and use `install` to copy and set permissions in one step

refactor installation script

---

log2ram.service

prevent the failed startup of the syslog-ng daemon, if it's been used instead of the default rsyslog.

start service before syslog-ng service too

---

log2ram.service

#83 At system shutdown log2ram should wait until journald has shutdown before syncing back to disk, otherwise it will sync an unclosed journal log.

Make log2ram shutdown after journald has shutdown

---

README.md

Need to use `sudo apt` if not root user. proceeding 2 lines already incorporate `sudo` commands so for consistency these lines should be `sudo` too.
Long time user of L2R but first time installing with apt.
bash commands in the install guide fail with permission denied error as apt is unable to lock files for update, likewise `apt install` and thus `apt remove` should also be `sudo` assuming the norm is a non-root user.
```
pi@raspberrypi:~ $ apt update
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: …
```

root privileges required for apt

---

README.md

The "OnCalendar=" directive is repeatable, so we have to add an empty one before to override. I also changed the time to match the commit c92e706.

added an empty OnCalendar= directive and move timer to 5 min

---

README.md
log2ram
log2ram.conf

This PR restores the ability to use `cp` instead of `rsync` for syncing files between the disk and the RAM. The parameter `USE_RSYNC` that controlled whether `rsync` is used was removed in 1.6.1.
Any parameter changes need to respect the former config default of `USE_RSYNC=false`. Many users won't knowingly agree to configuration file changes that remove a parameter that gave them a greater set of choices.
The restored parameter is intentionally commented out, respecting the removal of the parameter in post 1.6.1 `log2ram.conf` that defaulted to `rsync` for file transfers when installed. The default from pre 1.6.1 `log2ram.conf`, that is `USE_RSYNC=false`, is honoured.
Now `rsync` runs whenever `USE_RSYNC` is unset or missing (post 1.6.1 default in `log2ram.conf`) or set to true (case …

Restore RSYNC for backwards compatibility

---

install.sh

We have an auto-configuration process that preps for `log2ram` by creating its `.conf` file before installation (sets the size to 100M for instance). Currently, the installation of Log2Ram blows this configuration away and installs the default configuration, which then fails to mount on reboot due to its small size. This adds a simple check before installing the `log2ram.conf` file.

Check to see if conf file already exists before installing it.

---

build-packages.sh
install.sh
log2ram
log2ram.conf
log2ram.service
uninstall.sh

I have noticed that the naming of the functions as well as the indentation of the source code is very inconsistent. I have reworked this and attached a Doxygen compatible documentation to the functions.

Reformatted and refactored some files

---

README.md
log2ram

As I encountered an error where I tried to start log2Ram on a new system I added a more helpful output to the huge file failure in the syncFromDisk function.
And also an example command to flush the systemd journal as this was the culprit in my case.
May be this helps someone that, as I did, stumble for a few minutes while searching for the cause. (As one might be able to determine, it was the systemd journal growing to a huge size while containing nothing usefull at all on a new, empty, and unused system...)

Added more output on start failure

---

log2ram.conf

This pull request introduces a series of comment updates in the configuration files to improve clarity and readability. 
By enhancing the documentation directly within the configuration files, we can reduce the learning curve and help prevent configuration errors.
The changes should make it easier to setup log2ram, especially for new users or those not familiar with the more technical aspects of system configuration. 
The revisions provide concise, clear explanations of configuration settings. This includes specifying the purpose and implications of each setting, offering examples where applicable, and outlining the effects of different configurations on system behavior. 
Thankyou,
Adam

Config file update

---

log2ram

See issue  #138.
Right now, big sparse files (e.g. log files with big "holes" in them, like `/var/log/lastlog` when users/groups with large ids exist) take up much space when written to disk, because they are written as regular files, not sparse files.
`rsync` supports `--sparse` in combination with `--inplace` [since version 3.1.3](https://github.com/WayneD/rsync/commit/f3873b3d88b61167b106e7b9227a20147f8f6197) which was published [early 2018](https://github.com/WayneD/rsync/releases/tag/v3.1.3).

Handle sparse files correctly

---

ansible_playbook/install_log2ram.yml

- Added an Ansible task to install the prerequisite apt package 'gnupg', (Required by task: 'Add gpg key').
- Matched the Ansible playbook settings with the Log2Ram config defaults to ensure consistency and predictability. 
- Updated the playbook to use `NOTIFICATION=` instead of the incorrect `MAIL=` parameter. 
- Added the `NOTIFICATION_COMMAND=` setting to allow users to specify custom commands for notifications.

Ansible yaml update
